GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks/3982d5a8-e556-4f64-b1fe-c6d8814f1866

###
DELETE http://localhost:3000/tasks/2a4005d8-b33e-43d2-9105-02557e755919

###
POST http://localhost:3000/tasks

{
  "name": "sample task",
  "description": "sample task description",
  "categories": ["work"]
}

###
PUT http://localhost:3000/tasks/3982d5a8-e556-4f64-b1fe-c6d8814f1866

{
  "name": "updated task",
  "description": "sample task description",
  "categories": ["work"]
}
