GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks/1

###
DELETE http://localhost:3000/tasks/1

###
POST http://localhost:3000/tasks

{
  "name": "sample task",
  "description": "sample task description",
  "categories": ["work"]
}

###
PUT http://localhost:3000/tasks

{
  "id": "1",
  "name": "updated task",
  "description": "sample task description",
  "categories": ["work"]
}
